name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  JAVA_VERSION: 21

jobs:
  test:
    name: Build and test
    runs-on: big

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: ${{ env.JAVA_VERSION }}
          cache: sbt

      - name: Setup Sbt
        uses: sbt/setup-sbt@v1

# Needed for the integration tests
#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v1
#        with:
#          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
#
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v1
#        with:
#          project_id: pre-production-project-id

      - name: Build and test
        id: run_tests
        env:
          RUN_INTEGRATION_TESTS: false
        run: |
          set -o pipefail
          sbt clean test
          # sbt package bq-writer/docker:publish gcs-writer/docker:publish
